### ISSUE TITLE
error

### ISSUE THREAD

**Issue by HellishFeline** [JunkMeal/duolingo-plus#2]
is there any chance i can contact you on discord for 1 to 1 support?

**Comment by JunkMeal** [comment]
Sorry that I didn't reply in so long.
I recently made an update, so try it and if it doesn't work, my discord is JunkMeal#5421.
Also, I am going to make a V2 soon that should work for everyone and will be much faster.

**Comment by JunkMeal** [comment]
I just released V2, please use it instead.
